FROM node:18-alpine 

# 1. Use a specific, lightweight version (Alpine) to save disk space
WORKDIR /app

# 2. Optimization: Copy package files FIRST. 
# This leverages Docker Caching so 'yarn install' only runs if dependencies change.
COPY package.json yarn.lock* ./

# 3. Install dependencies and nodemon
RUN yarn install && yarn global add nodemon 
RUN npm install cors

# 4. Copy the rest of the source code
COPY . .

# 5. Blueprint Port
EXPOSE 4000

# 6. Runtime command
CMD ["nodemon", "src/server.js"]